#!/bin/bash


fetch_latest_changes() {
    git fetch origin master
}


get_latest_tag() {
    latest_tag=$(git describe --tags --abbrev=0)
    echo "$latest_tag"
}

increment_version() {
    version=$1
    part=$2

    if [[ ! "$version" =~ ^v([0-9]+)\.([0-9]+)\.([0-9]+)$ ]]; then
        echo "Invalid version format: $version"
        exit 1
    fi

    major="${BASH_REMATCH[1]}"
    minor="${BASH_REMATCH[2]}"
    patch="${BASH_REMATCH[3]}"

    case "$part" in
        "major")
            ((major++))
            minor=0
            patch=0
            ;;
        "minor")
            ((minor++))
            patch=0
            ;;
        "patch")
            ((patch++))
            ;;
        *)
            echo "Invalid part: $part"
            exit 1
            ;;
    esac

    echo "v$major.$minor.$patch"
}

fetch_latest_changes

latest_tag=$(get_latest_tag)

new_tag=$(increment_version "$latest_tag" "patch")

git tag "$new_tag"
git push origin "$new_tag"

echo "Created and pushed tag: $new_tag"
