name: "tagged-release"

on:
    push:
        tags:
            - "v*"

jobs:
    tagged-release:
        if: startsWith(github.ref, 'refs/tags/')
        permissions: 
            contents: write
            actions: write
        name: "Tagged Release"
        runs-on: "ubuntu-latest"

        steps:
        - uses: actions/checkout@v4
        - uses: actions/setup-node@v4
          with:
            node-version: '20.x'
        - name: Bump Version of package.json
          uses: ramonpaolo/bump-version@v2.3.1
          with:
            tag: ${{ github.ref_name }}
            commit: true
            branch_to_push: 'master'
        - run: |
            npm install -g @vscode/vsce
            npm install
            cd web
            npm install
            npm run build
            cd ..
            vsce package
        - name: Build Changelog
          id: github_release
          uses: mikepenz/release-changelog-builder-action@v4
          with:
            commitMode: true
            configurationJson: |
              {
                "template": "#{{CHANGELOG}}",
                "categories": [
                  {
                      "title": "## 🚀 Features",
                      "labels": ["feat", "feature"]
                  },
                  {
                      "title": "## 🐛 Fixes",
                      "labels": ["fix", "bug"]
                  },
                  {
                      "title": "## 🖍️ Other",
                      "labels": []
                  }
                ],
                "label_extractor": [
                  {
                    "pattern": "^(build|chore|ci|docs|feat|fix|perf|refactor|revert|style|test){1}(\\([\\w\\-\\.]+\\))?(!)?: ([\\w ])+([\\s\\S]*)",
                    "target": "$1"
                  }
                ],
              }
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        - name: Release
          uses: softprops/action-gh-release@v2
          with:
            repo_token: "${{ secrets.GITHUB_TOKEN }}"
            files: |
                *.vsix
